### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by akramfaresCap** [jenkins-khan/jenkins-php-api#39]
Running composer require jenkins-khan/jenkins-api shows this error:

[InvalidArgumentException]
Could not find package jenkins-khan/jenkins-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by MatCottet** [comment]
Hi!

Running _composer require jenkins-khan/jenkins-api=dev-master_ should made it.

**Comment by EvKoh** [comment]
+1
